// Nordic Secure DFU client over Web Bluetooth.
//
// Implements the minimum subset of the Nordic nRF5 SDK 17 Secure DFU protocol
// needed to upload a signed .zip package generated by create_dfu_package.py.
//
// Protocol reference: Nordic nRF5 SDK 17 / nrf_dfu_ble.c
//   Service:       0000FE59-0000-1000-8000-00805F9B34FB
//   Control Point: 8EC90001-F315-4F60-9FB8-838830DAEA50  (write + notify)
//   Packet:        8EC90002-F315-4F60-9FB8-838830DAEA50  (write-without-response)
//
// Control Point op codes (byte 0 of each request):
//   0x01 — Object Create        [type:1, size:4]
//   0x02 — Set PRN              [prn:2]
//   0x03 — Calculate CRC        []
//   0x04 — Execute Object       []
//   0x06 — Object Select        [type:1]
//   0x07 — MTU Get              []
// Responses arrive as notifications on Control Point, prefixed 0x60, then the
// request op, then a 1-byte result (0x01 = success).

const DFU_SERVICE_UUID   = '0000fe59-0000-1000-8000-00805f9b34fb';
const DFU_CONTROL_UUID   = '8ec90001-f315-4f60-9fb8-838830daea50';
const DFU_PACKET_UUID    = '8ec90002-f315-4f60-9fb8-838830daea50';

const OBJ_TYPE_COMMAND   = 0x01;
const OBJ_TYPE_DATA      = 0x02;

const OP_CREATE          = 0x01;
const OP_SET_PRN         = 0x02;
const OP_CALC_CRC        = 0x03;
const OP_EXECUTE         = 0x04;
const OP_SELECT          = 0x06;
const OP_RESPONSE        = 0x60;

const RESULT_SUCCESS     = 0x01;

// Chunk size when streaming bytes to the Packet characteristic. Must be
// <= (ATT_MTU - 3). With ATT_MTU=247 the ceiling is 244, but many Web
// Bluetooth stacks silently cap at 20-185 bytes per write. 20 is the
// safe floor that always works; bumping this up is a future perf win.
const PACKET_CHUNK_SIZE  = 20;

// ============================================================================
// CRC32 (IEEE 802.3, poly 0xEDB88320) — matches Nordic's nrf_crc32
// ============================================================================

const CRC32_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) {
      c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    }
    t[i] = c >>> 0;
  }
  return t;
})();

function crc32Update(crc, bytes) {
  crc = (~crc) >>> 0;
  for (let i = 0; i < bytes.length; i++) {
    crc = (CRC32_TABLE[(crc ^ bytes[i]) & 0xFF] ^ (crc >>> 8)) >>> 0;
  }
  return (~crc) >>> 0;
}

// ============================================================================
// Helpers
// ============================================================================

function u32le(buf, offset) {
  return (buf[offset] |
          (buf[offset + 1] << 8) |
          (buf[offset + 2] << 16) |
          (buf[offset + 3] << 24)) >>> 0;
}

function packU32(value) {
  return new Uint8Array([
    value & 0xFF,
    (value >>> 8) & 0xFF,
    (value >>> 16) & 0xFF,
    (value >>> 24) & 0xFF,
  ]);
}

function concatBytes(...arrays) {
  let total = 0;
  for (const a of arrays) total += a.length;
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrays) {
    out.set(a, off);
    off += a.length;
  }
  return out;
}

// ============================================================================
// DFU Client
// ============================================================================

class DfuClient {
  constructor(options = {}) {
    this.device = null;
    this.server = null;
    this.controlChar = null;
    this.packetChar = null;

    // Waiting for a single response at a time. Each Control Point write
    // triggers exactly one notification; serialise them via a promise queue.
    this._pendingResponse = null;

    this.onProgress = options.onProgress || (() => {});
    this.onStatus = options.onStatus || (() => {});
  }

  async connect() {
    this.onStatus('Requesting device…');
    this.device = await navigator.bluetooth.requestDevice({
      filters: [
        { namePrefix: 'DfuTarg' },
        { services: [DFU_SERVICE_UUID] },
      ],
      optionalServices: [DFU_SERVICE_UUID],
    });

    this.device.addEventListener('gattserverdisconnected', () => {
      this.onStatus('Disconnected.');
    });

    this.onStatus('Connecting…');
    this.server = await this.device.gatt.connect();

    this.onStatus('Finding DFU service…');
    const svc = await this.server.getPrimaryService(DFU_SERVICE_UUID);
    this.controlChar = await svc.getCharacteristic(DFU_CONTROL_UUID);
    this.packetChar  = await svc.getCharacteristic(DFU_PACKET_UUID);

    // Enable notifications on Control Point before any request.
    await this.controlChar.startNotifications();
    this.controlChar.addEventListener(
      'characteristicvaluechanged',
      (e) => this._onNotify(e.target.value)
    );

    this.onStatus('Connected.');
  }

  disconnect() {
    if (this.server && this.server.connected) this.server.disconnect();
  }

  // --------------------------------------------------------------------------
  // Notification handling
  // --------------------------------------------------------------------------

  _onNotify(dataView) {
    const buf = new Uint8Array(dataView.buffer);
    if (buf[0] !== OP_RESPONSE) {
      console.warn('DFU: unexpected notification', buf);
      return;
    }
    if (!this._pendingResponse) {
      console.warn('DFU: response with no pending waiter', buf);
      return;
    }
    const waiter = this._pendingResponse;
    this._pendingResponse = null;

    const reqOp = buf[1];
    const result = buf[2];
    if (result !== RESULT_SUCCESS) {
      waiter.reject(new Error(
        `DFU op 0x${reqOp.toString(16)} failed: result 0x${result.toString(16)}`
      ));
      return;
    }
    if (reqOp !== waiter.expectedOp) {
      waiter.reject(new Error(
        `DFU response mismatch: expected op 0x${waiter.expectedOp.toString(16)}, got 0x${reqOp.toString(16)}`
      ));
      return;
    }
    waiter.resolve(buf.slice(3));
  }

  _sendControl(bytes, expectedOp, timeoutMs = 10000) {
    if (this._pendingResponse) {
      throw new Error('DFU: another request already pending');
    }
    return new Promise(async (resolve, reject) => {
      const timer = setTimeout(() => {
        this._pendingResponse = null;
        reject(new Error(`DFU op 0x${expectedOp.toString(16)} timed out`));
      }, timeoutMs);

      this._pendingResponse = {
        expectedOp,
        resolve: (payload) => { clearTimeout(timer); resolve(payload); },
        reject:  (err)      => { clearTimeout(timer); reject(err); },
      };

      try {
        await this.controlChar.writeValue(bytes);
      } catch (err) {
        this._pendingResponse = null;
        clearTimeout(timer);
        reject(err);
      }
    });
  }

  // --------------------------------------------------------------------------
  // Object protocol
  // --------------------------------------------------------------------------

  async _selectObject(type) {
    const payload = await this._sendControl(
      new Uint8Array([OP_SELECT, type]),
      OP_SELECT
    );
    return {
      maxSize: u32le(payload, 0),
      offset:  u32le(payload, 4),
      crc:     u32le(payload, 8),
    };
  }

  async _createObject(type, size) {
    await this._sendControl(
      concatBytes(new Uint8Array([OP_CREATE, type]), packU32(size)),
      OP_CREATE
    );
  }

  async _calcCrc() {
    const payload = await this._sendControl(
      new Uint8Array([OP_CALC_CRC]),
      OP_CALC_CRC
    );
    return {
      offset: u32le(payload, 0),
      crc:    u32le(payload, 4),
    };
  }

  async _execute() {
    await this._sendControl(
      new Uint8Array([OP_EXECUTE]),
      OP_EXECUTE,
      20000 // execute can erase/write pages, allow more time
    );
  }

  async _setPRN(prn) {
    const payload = new Uint8Array([OP_SET_PRN, prn & 0xFF, (prn >>> 8) & 0xFF]);
    await this._sendControl(payload, OP_SET_PRN);
  }

  async _streamBytes(bytes) {
    // Packet char is write-without-response. Split into MTU-friendly chunks.
    for (let off = 0; off < bytes.length; off += PACKET_CHUNK_SIZE) {
      const chunk = bytes.subarray(off, Math.min(off + PACKET_CHUNK_SIZE, bytes.length));
      await this.packetChar.writeValueWithoutResponse(chunk);
    }
  }

  // --------------------------------------------------------------------------
  // High-level update flow
  // --------------------------------------------------------------------------

  async sendInitPacket(initBytes) {
    this.onStatus(`Sending init packet (${initBytes.length} bytes)…`);

    // Without PRN (Packet Receive Notification) the bootloader acks every
    // object via Execute only — simplest and fast enough for small payloads.
    await this._setPRN(0);

    const sel = await this._selectObject(OBJ_TYPE_COMMAND);
    if (initBytes.length > sel.maxSize) {
      throw new Error(`Init packet (${initBytes.length}B) exceeds object max ${sel.maxSize}B`);
    }

    await this._createObject(OBJ_TYPE_COMMAND, initBytes.length);
    await this._streamBytes(initBytes);

    const crc = crc32Update(0, initBytes);
    const remote = await this._calcCrc();
    if (remote.offset !== initBytes.length || remote.crc !== crc) {
      throw new Error(
        `Init CRC mismatch: sent ${initBytes.length}B crc 0x${crc.toString(16)}, ` +
        `remote offset ${remote.offset} crc 0x${remote.crc.toString(16)}`
      );
    }
    await this._execute();
    this.onStatus('Init packet accepted.');
  }

  async sendFirmware(firmwareBytes) {
    const total = firmwareBytes.length;
    this.onStatus(`Sending firmware (${total} bytes)…`);

    const sel = await this._selectObject(OBJ_TYPE_DATA);
    const chunkSize = sel.maxSize;

    let runningCrc = 0;
    let offset = 0;

    while (offset < total) {
      const chunk = firmwareBytes.subarray(offset, Math.min(offset + chunkSize, total));
      await this._createObject(OBJ_TYPE_DATA, chunk.length);
      await this._streamBytes(chunk);

      runningCrc = crc32Update(runningCrc, chunk);
      const remote = await this._calcCrc();
      if (remote.offset !== offset + chunk.length || remote.crc !== runningCrc) {
        throw new Error(
          `Data CRC mismatch at offset ${offset}: ` +
          `local=${offset + chunk.length}/0x${runningCrc.toString(16)}, ` +
          `remote=${remote.offset}/0x${remote.crc.toString(16)}`
        );
      }
      await this._execute();

      offset += chunk.length;
      this.onProgress(offset / total);
    }
    this.onStatus('Firmware transfer complete.');
  }

  async doUpdate({ initPacket, firmware }) {
    await this.sendInitPacket(initPacket);
    await this.sendFirmware(firmware);
    this.onStatus('Update applied — device will reboot.');
  }
}

// ============================================================================
// Zip unpacker helper — uses JSZip (loaded via CDN in index.html)
// ============================================================================

async function parseDfuZip(file) {
  if (typeof JSZip === 'undefined') {
    throw new Error('JSZip library not loaded');
  }
  const zip = await JSZip.loadAsync(file);

  const manifestFile = zip.file('manifest.json');
  if (!manifestFile) throw new Error('manifest.json missing from zip');
  const manifest = JSON.parse(await manifestFile.async('string'));

  const app = manifest.manifest && manifest.manifest.application;
  if (!app) throw new Error('manifest has no application section');

  const dat = zip.file(app.dat_file);
  const bin = zip.file(app.bin_file);
  if (!dat || !bin) throw new Error('zip missing .dat or .bin file referenced by manifest');

  return {
    initPacket: new Uint8Array(await dat.async('arraybuffer')),
    firmware:   new Uint8Array(await bin.async('arraybuffer')),
  };
}

// Export to window for index.html to use.
window.DfuClient = DfuClient;
window.parseDfuZip = parseDfuZip;
